version: "3.9"

services:
  web:
    build: .
    ports:
      - 40080:80
  mysql:
    image: mysql:5.6
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/docker.cnf
    command: ["--default-authentication-plugin=mysql_native_password","--sql-mode=ALLOW_INVALID_DATES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"]
    environment:
      - MYSQL_ROOT_PASSWORD=p4ssW0rd
    ports:
      - 127.0.0.1:3306:3306
